### ISSUE TITLE
Canon way to disable the built-in emoji

### ISSUE THREAD

**Issue by sisby-folk** [aratakileo/emogg#1]
This mod is really cool! We're kind of impressed at how not-a-stacked-birds-nest this codebase is given the results honestly 😅 

if there's not some way to filter out the emoji provided with the mod, would it be possible to split it out into a sample resource pack?

I was thinking of trying to cram the entirety of discord's default twemoji aliases into this if I can find a dump of them somewhere but having a clean start is probably a good idea first.

**Comment by aratakileo** [comment]
Thank you for your feedback! Since this is a beta version of the mod, its functionality is largely incomplete. I completely agree with you and I think that the mod should have a function to disable built-in emojis, as well as the ability to divide emoji into categories. I have already added your suggestions to the list of things to do in the future.

In the meantime, you can check out the example resourcepack below, which adds two new emojis, so you can create a resourcepack in its likeness and add your own emojis! To add your own emoji, you just need to add a new image with the extension `.png` for startic emoji or `.gif` for animated.

[Download example resourcepack](https://github.com/aratakileo/emogg/raw/main/emogg-addon.zip)

**Comment by sisby-folk** [comment]
Thanks!

**Comment by aratakileo** [comment]
I came back to you with a possible solution to your problem with the current version of the mod. You can remove the emojis you don't need directly from the mod files (as if you were editing a resource pack) and add the ones you need. This kind of change will not break the mod. If it is necessary to distribute the mod in a modified form, it is necessary to leave the data inside the "fabric.mod.json" in its original form. However, there is data that you can change – this is the name of the mod, its authors. The new data should include the values of the previous data. You can also replace the mod icon, but in this case the emogg logo should be visible on the new icon.

**Comment by sisby-folk** [comment]
It's cool we're mod developers we're familiar with ripping stuff out of mods or doing forks it's fine ^^ we're just interested in keeping an eye on when it's a mainline feature ^^ considering it for a modpack later on.

**Comment by aratakileo** [comment]
Okay, I get you. Thank you for your interest in the modification

**Comment by sisby-folk** [comment]
Hmm, this new method appears to be easier for users to disable the built in emoji, but substantially harder for modpack developers to disable the built in emoji. There's no easy way to ship a default-enabled builtin resource pack as default-disabled. 

I think the config value should be re-added, and it should be able to disable the registration of the builtin pack (or at least set it to default disabled)

**Comment by aratakileo** [comment]
What is the problem with the built-in resource packs being enabled by default? Previously, when there was a similar setup, but in the config, emojis were also enabled by default. I also ask you to take into account that resource packs are applied by default before the user gets access to the settings screen

**Comment by sisby-folk** [comment]
As specified - the config option allowed modpack developers (me) to disable the built in emoji for end users. This solution does ont allow that.

**Comment by aratakileo** [comment]
It turns out that you are going to implement disabling resource packs by editing the Emogg config file or by creating it, right?
