### ISSUE TITLE
Startup crash on 1.19.2 and 1.20.1 (1.0-beta2)

### ISSUE THREAD

**Issue by sisby-folk** [aratakileo/emogg#2]
Seems like all the mixins aren't 1.20.1 compatible anymore: https://mclo.gs/aLQoR9O

also tested on 1.19.2: https://mclo.gs/Eno0Ksa

 works fine on quilt 1.18.2.

**Comment by aratakileo** [comment]
Thank you so much for your feedback and for providing detailed information about the problem! 

You are correct in your assumption, but only by half. Mixins is still supported by mod loaders of up to date versions of Minecraft. In this situation, the problem is that the mod refers to the object responsible for rendering the chat interface, which exists in the Minecraft version 1.17.x - 1.18.x, but does not exist since version 1.19.x+, since, apparently, it has been replaced by another object.

At the moment, as a temporary solution to this problem, I can recommend that you roll back the mod to version 1.0-BETA.1 or lower. This will be necessary until this problem is fixed. I also bring to your attention that to solve this problem, the mod will be divided into two versions: version for Minecraft 1.17.x - 1.18.x and version for Minecraft 1.19.x+. I will get back to you with a new answer as soon as I manage to solve this problem.

**Comment by sisby-folk** [comment]
To clarify, a class annotated with @Mixin, or methods annotated with mixin annotations @Redirect @Inject etc, are often interchangeably referred to as "Mixins" themselves - so in this case what I meant was actually "Some of the mixins (in emogg 1.0-beta2) are not compatible with minecraft 1.19's code"

**Comment by aratakileo** [comment]
Well, thanks for the explanation 😅

**Comment by aratakileo** [comment]
I came back to you with a new answer. The new version of the mod is 1.0-BETA.3 supports minecraft versions 1.17.x - 1.19.x. According to the preliminary version, in subsequent versions the mod will support only 1.17.x-1.18.x and 1.19.1-1.19.4, respectively. Version 1.19 will not be supported. Support for versions 1.20.x is not planned at least until the release of the mod due to difficulties encountered when moving the mod to this version

**Comment by aratakileo** [comment]
Now emogg, from version 1.0-BETA.4 supports Minecraft version 1.20.x!
