### ISSUE TITLE
the emote menu is unsorted

### ISSUE THREAD

**Issue by Useless6uy** [aratakileo/emogg#21]
### Describe the bug

Emotes in the emote menu are not sorted by any discernible metric. (maybe order in the zip file?)
This means that for example all the clocks in the Twemogg emote packs are all over the place:
![image](https://github.com/aratakileo/emogg/assets/140262019/0af5da68-416b-419c-a1fb-db94497affa1)

The menu should probably be sorted alphabetically like the tab complete suggestions are.
But ideally both would use natural sorting.

### Which side have you encountered the bug on?

Client

### Steps to reproduce

1. Load the game with emogg
2. Open the emote menu
3. Observe the order of the emotes

### Additional context

Tested with no additional mods and a self complied version of b3901ad879eb4e110713dd351a31b75861960eba.
This bug might be depended on the OS and program the resource zip file has been packaged with.
I could observe the same issue with a custom emote pack too.

**Comment by aratakileo** [comment]
During implementation, it was not intended that emojis should be displayed in alphabetical order. The order that is now implemented in the emoji selection menu is provided by the Minecraft Resource Manager. Emoji suggestions look sorted alphabetically, due to the suggestions processing algorithm that is implemented in Minecraft.

From the point of view of UX, emojis really should be displayed in the emoji selection menu in alphabetical order. I will think about a possible implementation of sorting emojis in alphabetical order after they are categorized 😁
