### ISSUE TITLE
Mixin Crash on 1.20.4

### ISSUE THREAD

**Issue by MagicSweet-dev** [aratakileo/emogg#36]
### Describe the bug

Minecraft 1.20.4 crashed when I tried to start it with `emogg` and `fabric-api` installed due to failure in Mixins (i think).

### Which side have you encountered the bug on?

Client

### Steps to reproduce

1. Install emogg
2. Launch Minecraft 1.20.4
3. Get your game crashed (no crash report getting generated because mixin issue happens before actual Minecraft's logic for crash reports sets into place)

### Logs

https://mclo.gs/Ns7NNWl

**Comment by aratakileo** [comment]
Well, it's kinda weird... Perhaps, as a temporary solution, rolling back to an older version of the Fabric loader can help you

**Comment by MagicSweet-dev** [comment]
Russland кстати
![image](https://github.com/aratakileo/emogg/assets/49122140/22f7c433-2a1d-4450-a4bd-e0cc08ce64f8)

Я пожалуй на русиянском языке продолжу :/
--
Хммм, не знаю, как будто бы не связано с версией лоадера, но можно попробовать. На какую?

**Comment by MagicSweet-dev** [comment]
[Не прокатило](https://pastebin.com/cv1TZvqL)

**Comment by MagicSweet-dev** [comment]
Ну да, похоже так и есть.
1.20.4 закомменчено (почему-то), хотя в оригинальном коде игры уже всё поменяно. Щас поправлю, соберу, если что мерж реквест нажму
![image](https://github.com/aratakileo/emogg/assets/49122140/a0bd83f7-c364-45bf-bb53-df5ca38aa0a7)
![image](https://github.com/aratakileo/emogg/assets/49122140/d89cdce4-5e0a-401e-b939-497286c8d139)

**Comment by aratakileo** [comment]
I am sorry that communication in Russian causes you negative emotions related to the political situation. However, I ask you to draw your attention to the fact that Russian is not a language spoken exclusively in Russia. I would also prefer that we have a dialogue with you in English, because this project is part of the international GitHub community, and English is an international language.

Returning to the problem, based on the information that you provided and what can be seen from the logs, it seems that some mistakes were made when building the project for more current versions (1.20.2 - 1.20.4). There shouldn't be this problem in the next build, as I intend to pay more attention to these things in order to prevent such a problem from happening in the future.

p.s. I had previously used the Kiyv time zone, but noticed that in this time zone the time is translated twice a year and I decided to return to the Moscow time zone.

**Comment by MagicSweet-dev** [comment]
Yep, got it

**Comment by aratakileo** [comment]
Cool.

I would also like to suggest to you, if you are interested, to correct the translation of the mod in Ukrainian, as well as translate several new elements that have not yet been translated into Ukrainian.

p.s. I recommend comparing the changes with the move-to-elegance branch and directing PR to the same branch (since it is planned that this branch will soon be contributed to main. Also, the language files of this branch differ from main)

**Comment by MagicSweet-dev** [comment]
I'd be happy to, but I don't speak Ukrainian, unfortunately. The pfp is all about my political views.
I do, however, speak Mari but Minecraft itself does not support it so we're out of luck there.
(and nobody heard of it apparently lol)

**Comment by aratakileo** [comment]
Oh
