### ISSUE TITLE
Emoji text wrapping

### ISSUE THREAD

**Issue by sisby-folk** [aratakileo/emogg#5]
This might have been mentioned in your other comment, but the calculations for wrapping chat use the length of the emoji name rather than the width of the actual emoji, causing a situation like this one: 

![image](https://github.com/aratakileo/emogg/assets/55819817/fcc7e3e7-3777-4c6b-9e3c-ca2fc611ce0b)

where 4 emoji right next to eachother can't be displayed on one line.

Thanks again for the great mod!

**Comment by aratakileo** [comment]
Yes, that's right! Thank you for continuing to research the mod thoroughly! The reason for this bug is that the chat calculates the size of each line not from the length of the text display, but simply from the length of the text (length of String). As I have already said, I will deal with this kind of bugs later.

P. S. What does heart with gay men's pride flag with symbol of the note mean?

**Comment by sisby-folk** [comment]
[Flag](https://treblesand.dreamwidth.org/1177.html) & [Resource](https://morethanone.info)

**Comment by aratakileo** [comment]
Hey! Your problem is fixed in Emogg v1.0-BETA.7! You can already check this out on Minecraft v1.20-1.20.1. Don't forget to unzip!
[[Donwload now]](https://github.com/aratakileo/emogg/files/12264426/emogg-1.0-BETA.7-1.20.x.zip)
